const HTTPRespCodes = {
  HTTP_RESPONSE_SUCCESS: "200",
  HTTP_RESPONSE_CREATED: "201",
  HTTP_RESPONSE_ERROR: "400",
  HTTP_RESPONSE_UNAUTHORISED: "403",
  HTTP_RESPONSE_NOT_FOUND: "404",
  HTTP_RESPONSE_CONFLICT: "409",
};
export default HTTPRespCodes;
